# Generated by Django 3.0.4 on 2020-03-31 19:25
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GeneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comments', models.CharField(help_text='Comments on the gene', max_length=1000)),
                ('sequence', models.CharField(max_length=5000)),
            ],
        ),
    ]
